### ISSUE TITLE
In the android, when I click return key , the whole app will crash

### ISSUE THREAD

**Issue by toearth** [lulutia/react-native-tpicker#4]
When I click the textInput, the roller come up.At this time if I click the return button on my mobile phone , the whole will crash.

**Comment by toearth** [comment]
`<Modal
          animationType={this.state.animationType}
          transparent={true}
          visible={this.state.visible}
          onRequestClose={() => {this._setModalVisible(false)}}
        >`
I set the code above to the bottom, the problem has solved

```
        <Modal
          animationType={this.state.animationType}
          transparent={true}
          visible={this.state.visible}
          onRequestClose={() => {this._setModalVisible(false,'cancel')}}
        >
```

**Comment by lulutia** [comment]
ok, I understand what you have said. I will fix it in the next release. Thanks for your comment.
