### ISSUE TITLE
In android is moved text

### ISSUE THREAD

**Issue by Marcelrama** [lulutia/react-native-tpicker#5]
Hi, I'm using your library, thanks for the contribution, trying to adapt in android looks a bit fuzzy.
![captura de pantalla 2017-01-06 a las 3 30 54 p m](https://cloud.githubusercontent.com/assets/22013703/21730248/409328b8-d425-11e6-9b0e-02658c106b59.png)

**Comment by Jarda8** [comment]
It looks like the "overflow: hidden" prop  does't work without borders on Android and the "up" and "down" lists of items are not clipped. When I specified borders (by setting borderStyle or borderColor) for their views, it works well. But it is rather a hack. Maybe there is a beter solution.

**Comment by toearth** [comment]
I fellow borderColor solution, thanks.
